CREATE TABLE IF NOT EXISTS chat_context_snapshots (
    id BIGINT PRIMARY KEY,
    session_id BIGINT NOT NULL,
    covered_message_id BIGINT NOT NULL,
    summary_content MEDIUMTEXT NOT NULL,
    token_count INT NOT NULL,
    created_at DATETIME NOT NULL,
    KEY idx_context_snapshot_session (session_id, id),
    KEY idx_context_snapshot_covered (covered_message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS review_cards (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    knowledge_base_id BIGINT,
    document_id BIGINT,
    session_id BIGINT,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    tags_json JSON,
    source_message_id BIGINT,
    source_chunk_ids_json JSON,
    status VARCHAR(32) NOT NULL,
    card_state VARCHAR(32) NOT NULL,
    due_at DATETIME NOT NULL,
    last_reviewed_at DATETIME,
    stability DOUBLE NOT NULL,
    difficulty DOUBLE NOT NULL,
    elapsed_days INT NOT NULL DEFAULT 0,
    scheduled_days INT NOT NULL DEFAULT 0,
    reps INT NOT NULL DEFAULT 0,
    lapses INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    KEY idx_review_card_user_due (user_id, status, due_at),
    KEY idx_review_card_session (session_id),
    KEY idx_review_card_kb (knowledge_base_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS review_records (
    id BIGINT PRIMARY KEY,
    card_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating VARCHAR(32) NOT NULL,
    reviewed_at DATETIME NOT NULL,
    elapsed_days INT NOT NULL,
    scheduled_days_before INT NOT NULL,
    scheduled_days_after INT NOT NULL,
    stability_before DOUBLE NOT NULL,
    stability_after DOUBLE NOT NULL,
    difficulty_before DOUBLE NOT NULL,
    difficulty_after DOUBLE NOT NULL,
    state_before VARCHAR(32) NOT NULL,
    state_after VARCHAR(32) NOT NULL,
    due_at_before DATETIME NOT NULL,
    due_at_after DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    KEY idx_review_record_card (card_id, reviewed_at),
    KEY idx_review_record_user (user_id, reviewed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
